storeProject/storeApp/urls.py
from . import views as v
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',v.home, name='home' ),
    path('getgenre/<int:id>/', v.get_by_genre ,name='get_by_genre'),
    path('search', v.search_product ,name='search'),
    path('register',v.addUser,name='register'),
    path('login',v.login_view,name='login'),
    path('logout',v.logout_view,name='logout'),
    path('addcart/<int:id>/',v.add_cart,name='addCart'),
    path('order',v.my_order,name='morder'),
    path('cart',v.cart_list,name='crlist'),
    
]

storeProject/storeProject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('storeApp.urls','storeApp'), namespace='storeApp')),
    
   
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

storeProject/storeApp/models.py
from django.db import models
from django.contrib.auth.models import User

class userInfo(User):
    age = models.IntegerField()
    contact = models.IntegerField()
    gender = models.CharField(max_length=10)



class genre(models.Model):
    name = models.CharField(max_length=30)
    

    class Meta:
        db_table = 'genre'

    def __str__(self):
        return self.name

class book(models.Model):
    name =  models.CharField(max_length=30)
    price = models.IntegerField()
    img = models.ImageField(upload_to = 'images', default='')
    author = models.CharField(max_length=30)
    description = models.CharField(max_length=300, default='')
    genre = models.ForeignKey(genre, on_delete=models.CASCADE)

    class Meta:
        db_table = 'book'

    def __str__(self):
        return self.name

class cart(models.Model):
    book = models.ForeignKey(book, on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE )

    class Meta:
        db_table = 'cart'

    

class order(models.Model):
    total_bill = models.IntegerField()
    order_date = models.DateField(auto_now = True)
    order_status = models.CharField(max_length =30,default='processing')
    user = models.ForeignKey(User, on_delete = models.CASCADE)

    class Meta:
        db_table = 'order'

storeProject/storeApp/forms.py
from .models import userInfo,User,genre,book,cart
from django import forms
from django.contrib.auth.forms import UserCreationForm

class userForm(UserCreationForm):
    class Meta:
        model = userInfo
        fields = ['username','first_name','last_name','age','gender','contact','email']

class Login_form(forms.Form):
    username=forms.CharField(max_length=30)
    password=forms.CharField(widget =forms.PasswordInput)     


    

storeProject/storeApp/views.py
from django.shortcuts import render, HttpResponse, redirect

from .models import userInfo,User,genre,book,cart,order

from .forms import userForm,Login_form

# Create your views here.
def home(request):    
    gen=genre.objects.all()
    boo=book.objects.all()
    d={'gen':gen,'boo':boo}
    return render(request,'home.html',d)

def get_by_genre(request,id):
    gen=genre.objects.all()
    boo=book.objects.filter(genre=id)
    d={'gen':gen,'boo':boo}
    return render(request,'home.html',d)


def search_product(request):
    gen=genre.objects.all()
    boo=book.objects.all()

    if request.method=='POST':
        name=request.POST.get('srch')
        boo=book.objects.filter(name__contains=name)
        d={'gen':gen,'boo':boo}
        return render(request,'search.html',d)
    
    else:
        d={'gen':gen,'boo':boo}
        return render(request,'search.html',d)

def addUser(request):
    cl=genre.objects.all()
    if request.method=='POST':
        f= userForm(request.POST)
        f.save()
        d={'cl':cl}
        return render(request,'login.html',d)

    else:
        f=userForm
        d={'cl':cl,'form':f}
        return render(request,'form.html',d)

from django.contrib.auth import login as dj_login,logout as dj_logout,authenticate
def login_view(request):
    cl=genre.objects.all()
    if request.method=='POST':
        username=request.POST.get('username')
        password =request.POST.get('password')
        user = authenticate(request,username=username, password=password)
        if user is not None:
            dj_login(request,user)
            request.session['uid'] = user.id
            
            gen=genre.objects.all()
            boo=book.objects.all()
            d={'gen':gen,'boo':boo}
            return render(request,'home.html',d)
            #return redirect('/')
        else:
            return HttpResponse("InValid userName or password")
    else:
        f=Login_form
        d={'cl':cl,'form':f}
        return render(request,'login.html',d)

def logout_view(request):
    dj_logout(request)
    return redirect('/')


from django.contrib.auth.models import User
from .models import cart,order

def add_cart(request,id):
    b = book.objects.get(id = id)
    uid = request.session.get('uid')
    
    u = User.objects.get(id = uid)
    #create instance of model
    crt = cart()
    crt.user = u
    crt.book = b
    crt.save()
    return redirect('/')

def cart_list(request):
    uid = request.session.get('uid')
    if request.method == 'POST':

        my_ord = order()
        my_ord.total_bill =  request.POST.get('bill')   
        my_ord.user = User.objects.get(id = uid)
        my_ord.save()
        # crlist=Cart.objects.filter(user=uid)
        # for c in crlist:
        #     c.delete()
        cart_items =  request.POST.get('cart_items')   
        return redirect('/')

    else:
        cl = genre.objects.all()
        crlist = cart.objects.filter(user = uid)

        totalBill = 0
        for i in crlist:
            totalBill += i.book.price

    d = {'cl':cl, 'totalBill':totalBill, 'crlist':crlist}
    return render(request,'cartlist.html',d)

def my_order(request):
    cl=genre.objects.all()
    uid=request.session.get('uid')
    orlist=order.objects.filter(user=uid)
    d={'cl':cl,'orlist':orlist}
    return render(request,'orderlist.html',d)

storeProject/storeApp/templates/cartlist.html
{%extends 'navbar.html'%}
{% block css%}
    {% load static %}
        <link rel="stylesheet" href="{% static 'css/cart.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
    {% endblock %}

{%block main%}
<form method="POST">
    {%csrf_token%}    
    <!-- ------------------cart----start------------- -->
    <div class="basket">
        
        <div class="basket-labels">
          <ul>            
            <li class="item item-heading">Item</li>
            <li class="price">Price</li>
            <li class="quantity">Quantity</li>
            <li class="subtotal">Subtotal</li>
          </ul>
        </div>
        {%for i in crlist%}
            <div class="basket-product">
            <div class="item">
                <div class="product-image">
                <img src="{{i.img.url}} alt='img' class='product-frame'">
                </div>
                <div class="product-details">
                <h4><strong><span class="item-quantity"></span>  {{i.book.name}}</strong> </h4>
                <p><strong>product book</strong></p>
                <p>Product Code - {{i.id}}</p>
                </div>
            </div>
            <div class="price">{{i.book.price}}</div>
            <div class="quantity">
                <input type="number" name="cart_items" value="1" min="1" class="quantity-field">
            </div>
            <div class="subtotal">{{i.book.price}}</div>
            <div class="remove">
                <button>Remove</button>
            </div>
            </div>
        {% endfor %}
        
        
        
      </div>
      <aside>
        <div class="summary">
          <div class="summary-total-items"><span class="total-items"></span> Items in your Bag</div>
          <div class="summary-subtotal">
            <div class="subtotal-title">Subtotal</div>
            <div class="subtotal-value final-value" id="basket-subtotal"><input type="hidden" name="bill" value="{{totalBill}}">{{totalBill}}</div>
            <div class="summary-promo hide">
              <div class="promo-title">Promotion</div>
              <div class="promo-value final-value" id="basket-promo"></div>
            </div>
          </div>
          <div class="summary-delivery">
            <select name="delivery-collection" class="summary-delivery-selection">
                <option value="0" selected="selected">Select Collection or Delivery</option>
               <option value="collection">Collection</option>
               <option value="first-class">Delivery by Fedex</option>
               <option value="second-class">Delivery by Booked.in</option>
            </select>
          </div>
          <div class="summary-total">
            <div class="total-title">Total</div>
            <div class="total-value final-value" id="basket-total"><input type="hidden" name="bill" value="{{totalBill}}">{{totalBill}}</div>
          </div>
          <div class="summary-checkout">
            <button class="checkout-cta"><input class="checkout-cta" type="submit" value="PlaceOrder"></button>
          </div>
        </div>
      </aside>
      {% load static%}
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
    <!-- ------------------cart end------------------- -->
</form>
{%endblock%}

storeProject/storeApp/templates/form.html
{%extends 'navbar.html'%}
    {% block css%}
    {% load static %}
    <link  href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% endblock %}

{% load crispy_forms_tags %}

{%block main%}
<form method="POST">
    {%csrf_token%}
    <div class="container">
        <div class="row">
            <div class="col-8">
                {{form|crispy}}
            </div>
        </div>
    </div>
        
        
            <!-- <input type="submit">
            <input type="reset"> -->
            <button type="submit" class="btn btn-success">Save </button>
       
   
</form>

{%endblock%}

storeProject/storeApp/templates/home.html
{% extends 'base.html'%} 

{% block css%}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/shop-homepage.css' %}">
{% endblock %}


{% block content %}

<h2><a href="{% url 'storeApp:search' %}">Search for books</a></h2>

<div class="col-md-3">
    <p class="lead">genreName</p>
    <div class="list-group">
        {%for i in gen%}
        <a href="{%url 'storeApp:get_by_genre' i.id %}" class="list-group-item">{{i.name}}</a> {%endfor%}
    </div>
</div>
{%endblock%}


{%block main%} {%for i in boo%}
<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="{{i.img}}" alt="" width="300" height="200">
        <div class="caption">
            <h4 class="pull-right">{{i.price}}</h4>
            <h4><a href="#">{{i.name}}</a>
            </h4> 
            {% if user.is_authenticated %}
                <button onclick="incrementValue()"><a href="{%url 'storeApp:addCart' i.id %}" >Add to cart</a></button>  
            {% else %}
                <button><a href="{%url 'storeApp:login'%}">Add to cart</a></button>
            {% endif %}         
            <p>{{i.description}}</p>
        </div>
        <div class="ratings">
            <p class="pull-right">15 reviews</p>
            <p>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
            </p>
        </div>
    </div>
</div>
{%endfor%}



{%endblock%}


{% include 'footer.html' %}

storeProject/storeApp/templates/login.html
 {%extends 'navbar.html'%} 
    {% block css%}
    {% load static %}
    <link  href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% endblock %}

 {% block main %}
 {% load crispy_forms_tags %}
<form method="POST">
    {%csrf_token%}
    
    <div class="container">
        <div class="row">
            <div class="col-8">
                {{form|crispy}}
            </div>
        </div>
    </div>
            <button type="submit" class="btn btn-success">Save </button>
</form>
{%endblock%}

storeProject/storeApp/templates/orderlist.html
{%extends 'navbar.html'%} {%block main%} {%csrf_token%}
<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">totalBill</th>
        <th scope="col">Status</th>
        <th scope="col">OrderDate</th>
      </tr>
    </thead>
    <tbody>
        {%for i in orlist %}
      <tr>
        <th scope="row">{{i.id}}</th>
        <td>{{i.total_bill}}</td>
        <td>{{i.order_status}}</td>
        <td>{{i.order_date}}</td>
      </tr>   
      {%endfor%}   
    </tbody>
  </table>
{%endblock%}

storeProject/storeApp/templates/search.html
{%extends 'navbar.html'%}

{% block css%}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/shop-homepage.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js">
    <style>
    .form-control:focus {
  box-shadow: none;
}

.form-control-underlined {
  border-width: 0;
  border-bottom-width: 1px;
  border-radius: 0;
  padding-left: 0;
}
.form-control::placeholder {
  font-size: 1.6rem;
  color: #aaa;
  font-style: italic;
}
    </style>
{% endblock %}

{%block slider%}

<form method="POST">
    {%csrf_token%} 
    <!-- <div class="container">
        <div class="row">
            <div class="col-8">
                <input class="form-control"   name="srch">
            </div>
            <div class="col-4">
                <input class="form-control"  type="submit" value="Search">
            </div>
        </div>
    </div>       -->
    
        
            <div class="col-lg-8 mx-auto ">
                    <div class="bg-light rounded rounded-pill shadow-sm mb-4">
                          <input type="search" placeholder="What're you searching for?" name="srch"  class="form-control border-0 bg-light">
                    </div>
            </div>
            <div class="col-lg-4 mx-auto ">
                <button id="button-addon1" type="submit" class="btn btn-link text-primary"><i class="fa fa-search"></i></button>
            </div>
       
   
    
    
</form>
{%endblock%}
{%block main%} {%for i in boo%}

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="{{i.img}}" alt="" width="250" height="150">
        <div class="caption">
            <h4 class="pull-right">{{i.price}}</h4>
            <h4><a href="#">{{i.name}}</a>
            </h4>
            <p>{{i.description}}</p>
        </div>
        <div class="ratings">
            <p class="pull-right">15 reviews</p>
            <p>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
            </p>
        </div>
    </div>
</div>
{%endfor%} {%endblock%}

storeProject/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shop Homepage Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
   
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/shop-homepage.css' %}">
    <link rel="stylesheet" href="{% static 'css/cart-add.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link  href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block css%}
    {% endblock %}

</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'storeApp:home' %}">Booked.in</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#about">About</a>
                    </li>
                    <li><a href="#services">Store</a>
                    </li>
                    <li><a href="#contact">Contact</a>
                    </li>
                    {%if user.is_authenticated%}

                    <li><a href="{%url 'storeApp:crlist'%}">Cart</a>
                    </li>
                    <li><a href="{%url 'storeApp:morder'%}">My Order</a>
                    </li>
                    <li><a href="#">FeedBack</a>
                    </li>
                    <li><a href="{%url 'storeApp:logout'%}">Logout</a>
                    </li>
                    {%else%}
    
                    <li><a href="{%url 'storeApp:register'%}">Register</a>
                    </li>
                    <li><a href="{%url 'storeApp:login'%}">Login</a>
                    </li>
    
                    {%endif%}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">

        <div class="row">
            {% block content%}
                {% endblock %}

            

            <div class="col-md-9">

                <div class="row carousel-holder">

                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="item active">
                                    <img class="slide-image" src="{% static 'images/poster.jpg' %}" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    </div>

                </div>
                <div class="row">
                    {% block main%}
                      {% endblock %}

                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <h4><a href="#">Best books 2020</a>
                        </h4>
                        <p>Check out our curated list on this years best picks</p>
                        <a class="btn btn-primary" target="_blank" href="http://maxoffsky.com/code-blog/laravel-shop-tutorial-1-building-a-review-system/">View </a>
                    </div>

                </div>
                <div class="cd-cart__trigger">
                    <a href="{%url 'storeApp:crlist'%}" class="cd-cart text-replace">
                        <i class="fa fa-shopping-cart fa-3x"></i>                                             
                    </a>                   
               </div>
               <div class="cd-cart__count ">
                  <span  class="badge badge-warning">0{{item_numbers}}</span>                   
               </div>

        </div>

    </div>
    <!-- /.container -->

    <div class="container">

        <hr>

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Company 2013 - Template by <a href="http://maxoffsky.com/">Maks</a>
                    </p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <!-- JavaScript -->
    {% load static%}
    <script type="text/javascript" src="{%  static 'js/jquery-1.10.2.js' %}"></script>
    <script type="text/javascript" src="{%  static 'js/bootstrap.js' %}"></script>
    <script  type="text/javascript" src="{% static 'js/cart-add.js'%}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
   

</body>

</html>

storeProject/templates/base1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css%}
    {% endblock %}
    <title>Document</title>
</head>
<body>
    <div class="container ">
        <div class="row">
            {%block slider%}
            {%endblock%}
        </div>
    </div>
    
    <div class="container">
        <div class="row ">
            {%block main%}
            {%endblock%}
        </div>
    </div>
    
    
</body>
</html>

storeProject/templates/navbar.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shop Homepage Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
   
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/shop-homepage.css' %}">
    <link  href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block css%}
    {% endblock %}

</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'storeApp:home' %}">Booked.in</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#about">About</a>
                    </li>
                    <li><a href="#services">Store</a>
                    </li>
                    <li><a href="#contact">Contact</a>
                    </li>
                    {%if user.is_authenticated%}

                    <li>
                        <a href="{%url 'storeApp:crlist'%}" class="cd-cart__trigger text-replace">
                            Cart</a>
                                                  
                    </li>
                    <li><a href="{%url 'storeApp:morder'%}">My Order</a>
                    </li>
                    <li><a href="#">FeedBack</a>
                    </li>
                    <li><a href="{%url 'storeApp:logout'%}">Logout</a>
                    </li>
                    {%else%}
    
                    <li><a href="{%url 'storeApp:register'%}">Register</a>
                    </li>
                    <li><a href="{%url 'storeApp:login'%}">Login</a>
                    </li>
    
                    {%endif%}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <div class="container ">
        <div class="row mb-10">
            {%block slider%}
            {%endblock%}
        </div>
        <div class="row">
            {% block main%}
              {% endblock %}
        </div>
    </div>



   
</body>

</html>